### ISSUE TITLE
Projeto

### ISSUE THREAD

**Issue by JonatanGomesF** [jonatancolt/ITU-ADS-242-GRUPO-02#26]
Site criado para ajudar pessoas que buscam informações sobre suas dificuldades, e que precisam de auxilio para reduzir seu problema que somente ela mesma enfrenta; no projeto será inserido um mecanismo de quiz, através de uma tela, e que a pessoa consegue interagir com o site, a fim de conseguir entender seus problema.

**Comment by LucasPedro26** [comment]
' 1 Correção; Termo citado "Aplicativo". Substituído para site, com o devido proposito de acesso através do navegador.
' 2 Correção; Termo citado "literalmente estão sem nenhum recurso". Substituído para buscam informações sobre suas dificuldades. tendo foco em formalidade textual. 

#Aprovado
