### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by JonatanGomesF** [jonatancolt/ITU-ADS-242-GRUPO-02#27]
Conseguir auxiliar pessoas e trazer suas realidades que somente elas mesmas enfrentam, através dessa ferramenta que tem por meio ajudar a reduzir e tratar seus problemas.

  -visando no engajamento da ferramenta nacional, se por objetivo for um sucesso , tendo a disponibilidade no exterior.

**Comment by LucasPedro26** [comment]
# Aprovado
