### ISSUE TITLE
Conteúdo

### ISSUE THREAD

**Issue by JonatanGomesF** [jonatancolt/ITU-ADS-242-GRUPO-02#29]
Quiz com funcionalidades de identificar quais seriam os problemas do Usuário.
Aplicação Web: na tela (guias) que mostram ao Usuário qual o seu tipo de problema. Palestras, Dicas, novos hábitos, conteúdos informativos e testemunhos de pessoas que já passaram pela mesma situação.

**Comment by LucasPedro26** [comment]
Correção; "ouvintes e conselhos superficiais". Substituído para  identificar quais seriam os.
